# Generated by Django 5.1.4 on 2025-01-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskdetail_notes_alter_taskdetail_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
